### PR TITLE
added source option can be a function

### PR DESCRIPTION
**Pull request by ivoba**
By passing _source_ as a function you can now choose the source conditionaly.
F.e. if role is COMPANY use property title, if not use firstName+LastName.

Function can be passed alternativly to String or Array.

### CODE REVIEW

**Comment by ivoba** [comment]
thanks for merging, can you tag a release, pls

**Comment by dariuszp** [comment]
Sorry, I didn't had time recently to maintain this module. I will tag it today this evening. At the weekend I will try to rework it a little without braking it and write tests to cover use cases.

**Comment by ivoba** [comment]
thanks for the tag, on npm its still on 0.7.2?
does npm need some notification?

**Comment by dariuszp** [comment]
Hi, I've updated npm. Just remember that this extension is not stable (0.7). I didn't had time to finish it properly and I'm too busy to spend time on it. Extension is not unit tested at the moment.

**Pull request merged**
